### ISSUE TITLE
eth.log from micks pc

### ISSUE THREAD

**Issue by mcgasson** [avastmick/ethereum-local-testnet#27]
[eth.log.txt](https://github.com/avastmick/ethereum-local-testnet/files/258870/eth.log.txt)

**Comment by avastmick** [comment]
This is due to the version of Geth - 1.4. I have to remove the deprecated flag and use init to remove the warning message that is busting the enode URLS

**Comment by mcgasson** [comment]
Yep, 1.4.3 is now the stable release not dev

Geth
Version: 1.4.3-stable
Protocol Versions: [63 62 61]
Network Id: 1
Go Version: go1.6.1
OS: linux
GOPATH=
GOROOT=/usr/lib/go-1.6
